---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(app-name)
  labels:
    app: $(label)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $(label)
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 80
        - name: rss-reader
          image: nickchase/rss-php-nginx:v1
          ports:
            - containerPort: 88